#!/bin/bash

echo "Copying video: " forest_jester-dv.mov
mkdir -p /srv/local/macher/
mkdir -p /srv/local/macher/bench3/
mkdir -p /srv/local/macher/bench3/output/
rm -f /srv/local/macher/bench3/output/*.log
mkdir -p /srv/local/macher/bench3/tempvids/
cp ../forest_jester-dv.mov /srv/local/macher/bench3/
header='configurationID,H264,no_8x8dct,no_asm,no_cabac,no_deblock,no_fast_pskip,no_mbtree,no_mixed_refs,no_weightb,rc_lookahead,ref,size,usertime,systemtime,elapsedtime'
x64configs=`ls *.sh`
for i in {1..5}
do
csvOutput="x264-results$i.csv"
touch $csvOutput
cat /dev/null > $csvOutput
echo "$header" > $csvOutput
for x264config in $x64configs
do
echo "Processing: " $x264config
   csvLine=`bash $x264config`
   echo "$csvLine" >> $csvOutput
done
tar cvf "oX264-results$i.tar.gz" /srv/local/macher/bench3/output/*.log
done
rm /srv/local/macher/bench3/forest_jester-dv.mov
rm -rf /srv/local/macher/bench3/
echo "Deleting bench folder"
